id = "netcoredbg"
name = "NetCoreDbg"
version = "1.1.0"
schema_version = 1
authors = ["nulifyer <zed-csharp-ext.caress448@passmail.net>"]
description = "NetCoreDbg debugger extension for .NET applications"
repository = "https://github.com/qwadrox/zed-netcoredbg"

[debug_adapters.netcoredbg]
schema_path = "debug_adapter_schemas/netcoredbg.json"
